### ISSUE TITLE
连接不上mysql数据库

### ISSUE THREAD

**Issue by zxl78585** [aberic/fabric-net-server#23]
我想问下，docker中有数据库吗？直接启动docker就可以了，还是说需要自己在本机安装一个mysql数据库呢？

**Comment by zxl78585** [comment]
@aberic 我现在连接自己的数据库，也起来了，没报错，但是外面访问不到，我是在虚机中起的，防火墙已经开放了8080端口了。我在虚机里面netstat -lnp  | grep 8080，没有查到端口。我用的是RC7

**Comment by zxl78585** [comment]
@aberic 刚又查了一下，虚机里面能查到8080端口了，但是我本机还是telnet不通到8080口上

**Comment by aberic** [comment]
telnet的ip需要是你的物理机网卡绑定的内网ip，查下

**Comment by zxl78585** [comment]
@aberic 我telnet的就是物理机的真正的网卡的地址。先不管他了，我在虚机里面装了一个界面，可以访问到了， 先上去看看，剩下的以后再研究。

**Comment by zxl78585** [comment]
@aberic  CA sk文件从哪里搞？

**Comment by aberic** [comment]
https://github.com/aberic/fabric-net-server/wiki/HyperLedger-Fabric%E7%BD%91%E7%BB%9C%E4%BA%A4%E4%BA%92#%E5%AF%B9%E8%B1%A1%E5%AD%97%E6%AE%B5%E9%83%A8%E5%88%86%E9%87%8A%E4%B9%89
