### ISSUE TITLE
wiki安装部署页面建议增加mysql环境变量

### ISSUE THREAD

**Issue by okzhchy** [aberic/fabric-net-server#26]
Docker-compose的docker-fns.yaml，没有加mysql环境变量的选项，建议加上，否则不知道应用如何连接数据库。如下：

    environment:
      - USERNAME=admin
      - PASSWORD=123456
      - MYSQL_DATA_SOURCE_URL=jdbc:mysql://localhost:3306/fns?serverTimezone=UTC&useSSL=false
      - MYSQL_DATA_SOURCE_USERNAME=root
      - MYSQL_DATA_SOURCE_PASSWORD=123456

**Comment by aberic** [comment]
你好，这是master(RC7)的内容，目前还没正式发包
