### ISSUE TITLE
接口query错误

### ISSUE THREAD

**Issue by xiaozehao** [aberic/fabric-net-server#28]
### 首页区块信息都能正常显示
![image](https://user-images.githubusercontent.com/9866297/46067999-b8925900-c1aa-11e8-8972-0c3d99530d77.png)
### 执行链码
![image](https://user-images.githubusercontent.com/9866297/46068018-c5af4800-c1aa-11e8-949b-6713d21a5797.png)
### 查询链码
![image](https://user-images.githubusercontent.com/9866297/46068035-cf38b000-c1aa-11e8-93e1-e2c635282e15.png)

为什么查询链码数据的时候会出现这个问题？ @AbericYang @aberic

**Comment by aberic** [comment]
执行和查询的方法都是同一个吗？

**Comment by xiaozehao** [comment]
Invoke方法
![image](https://user-images.githubusercontent.com/9866297/46068855-b5986800-c1ac-11e8-90f5-e3f339f3ca59.png)
queryAllCars方法
![image](https://user-images.githubusercontent.com/9866297/46068908-d9f44480-c1ac-11e8-86f2-8c0350fd49b9.png)

**Comment by aberic** [comment]
我看你有四个节点，执行invoke的节点和query的节点一样吗？p0o1节点证书部署检查一下是否有误

**Comment by xiaozehao** [comment]
这是我用java的sdk执行queryByChainCode方法
![image](https://user-images.githubusercontent.com/9866297/46070950-86382a00-c1b1-11e8-91ed-3f982a270519.png)

**Comment by aberic** [comment]
刚才本地测试了一次，没有复现你的问题。
是否使用fns的容器跑的？尝试一下跑源码，debug一下问题所在

**Comment by xiaozehao** [comment]
我debug发现，其实接口已经返回成功。
![image](https://user-images.githubusercontent.com/9866297/46119230-a95beb80-c23c-11e8-9661-833b41e6107d.png)
但是校验数据的时候有问题
![image](https://user-images.githubusercontent.com/9866297/46119260-c42e6000-c23c-11e8-8bb8-9d951dc3e5b9.png)
checkVerified=true, proposalResponse.isVerified() = false

**Comment by aberic** [comment]
你使用的是Fabric1.2的版本吗？先前出现过这样的情况，对版本做了判断临时处理了下，后来更新SDK到1.2，就切换回去了，看样子官方SDK做了新的验证方案。
可以参考https://github.com/aberic/fabric-net-server/blob/1.0-RC5/fabric-sdk-service/src/main/java/cn/aberic/fabric/sdk/IntermediateChaincodeID.java这个临时处理下，或者根据官方SDK的校验方案做下兼容
