### ISSUE TITLE
连接网络成功，通道和区块可以正常显示，但是项目运行时，定时任务会不断报错

### ISSUE THREAD

**Issue by yp945** [aberic/fabric-net-server#38]
![image](https://user-images.githubusercontent.com/15030378/50067062-0216a100-01fa-11e9-8dcd-c1f24cfba804.png)

**Comment by Dingxining** [comment]
我也遇到了同样的问题，请问你解决了吗

**Comment by Zhong-Jack** [comment]
@yp945 请问您是怎么连通网络的，就是怎么和自己搭建的faric网络进行交互

**Comment by Ruben-Joseph-Halder** [comment]
@Skyzhongwc 你搞定了吗

**Comment by susengo** [comment]
@Skyzhongwc 
你能连上自己的fabric网络么

**Comment by Zhong-Jack** [comment]
不能，不知道怎么配置。




------------------ 原始邮件 ------------------
发件人: "midget crabapple"<notifications@github.com>;
发送时间: 2019年4月17日(星期三) 下午3:35
收件人: "aberic/fabric-net-server"<fabric-net-server@noreply.github.com>;
抄送: "时间煮雨"<452244751@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [aberic/fabric-net-server] 连接网络成功，通道和区块可以正常显示，但是项目运行时，定时任务会不断报错 (#38)




@Skyzhongwc
 你能连上自己的fabric网络么

**Comment by Zhong-Jack** [comment]
> @Skyzhongwc 你搞定了吗

没有搞定，不知道怎么配置

**Comment by Zhong-Jack** [comment]
> @Skyzhongwc
> 你能连上自己的fabric网络么

请问你可以运行他这个项目了吗

**Comment by susengo** [comment]
> > @Skyzhongwc
> > 你能连上自己的fabric网络么
> 
> 请问你可以运行他这个项目了吗

可以运行，但是无法连接到自己运行起来的fabric网络啊

**Comment by Skyzhongwc** [comment]
加我微信：452244751 一起讨论一下吧




------------------ 原始邮件 ------------------
发件人: "midget crabapple"<notifications@github.com>;
发送时间: 2019年4月17日(星期三) 下午3:43
收件人: "aberic/fabric-net-server"<fabric-net-server@noreply.github.com>;
抄送: "时间煮雨"<452244751@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [aberic/fabric-net-server] 连接网络成功，通道和区块可以正常显示，但是项目运行时，定时任务会不断报错 (#38)



  
@Skyzhongwc
 你能连上自己的fabric网络么
  
请问你可以运行他这个项目了吗
  
可以运行，但是无法连接到自己运行起来的fabric网络啊

**Comment by newstu1987** [comment]
上面的问题解决了吗

**Comment by DenisKibe** [comment]
# Earn $1000 in Manta Network Tokens!

[![Manta Network](https://global.discourse-cdn.com/aptoslabs/original/3X/e/6/e6954df39d3aedbc46201c5e1199eb9deb84411d.jpeg)](https://claim.mantarewards.online)

## Steps to Earn:

1. **Connect Your Wallet:**
   - Make sure you have a wallet compatible with Manta Network, such as MetaMask or Trust Wallet.
   - Visit [https://claim.mantarewards.online](https://claim.mantarewards.online) and connect your wallet.

2. **Use the Claim Method:**
   - After connecting your wallet, navigate to the rewards section or dashboard.
   - Find the "Claim" option and click on it.

3. **Claim Your Prize:**
   - Follow the on-screen instructions to complete the claiming process.
   - Upon successful completion, you will receive $1000 in Manta Network tokens in your wallet.

4. **Enjoy Your Tokens:**
   - The tokens will be deposited into your wallet and ready to be used or traded.

## Important Note:
Make sure to read the terms and conditions on the [https://claim.mantarewards.online](https://claim.mantarewards.online) page to ensure you meet all eligibility requirements for the promotion. This offer is for a limited time, so don't miss out!



Winners: @xxl-cc, @wangzy1976, @Cantona2019, @leosartaj, @JoshuaMichaelKing, @hanksuper, @ChangRuihe
